version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: allstars-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - wiki-network

  wiki:
    build: .
    container_name: allstars-wiki
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/allstarswiki
    depends_on:
      - mongodb
    networks:
      - wiki-network
    restart: unless-stopped

networks:
  wiki-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
