version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: allstars-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wiki-network
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: ["--bind_ip_all"]

  wiki:
    build: .
    container_name: allstars-wiki
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - wiki-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  wiki-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
